### ISSUE TITLE
Support Azure CLI 64bit installation

### ISSUE THREAD

**Issue by williamoconnorme** [peterjohnsonme/chocolatey-packages#34]
Since the release of azure-cli v2.51.0, a 64bit MSI installer is available. Installing the azure-cli choco package with latest version 2.53.0 will install by default the 32bit version on a 64 bit operating system.

This package should be updated to include a `Url64bit` and `Checksum64 ` parameters for `Install-ChocolateyPackage` to ensure the correct OS architecture is installed.

**Comment by peterjohnsonme** [comment]
Thanks for the note here! I'll update it this week to include both versions.  If you need it quicker, happy to take a PR.

**Comment by flcdrg** [comment]
Probably need to test the upgrade scenario - I have a feeling the old 32 bit install might be left in place if a new package version now includes a 64 bit installer.

**Comment by flcdrg** [comment]
Here's an example of a package that has a manual uninstall step - https://github.com/TheCakeIsNaOH/chocolatey-packages/blob/master/anydesk.install/tools/chocolateyinstall.ps1 (though I don't think that example is checking 32 bit version)

Also this advice from @TheCakeIsNaOH (from the Chocolatey Discord)

> When checking if the 32 bit version should be removed, make sure to include the forcex86 flag as well as the system architecture. So (Get-OSArchitectureWidth -compare 64) -and ($env:chocolateyForceX86 -eq $false) or similar

**Comment by peterjohnsonme** [comment]
I tested the upgrade scenario on a 64-bit system and a simple choco-install of the 64-bit version properly uninstalled the x86 version - automatically.  An updated 2.53 package with 64-bit support has been pushed to the community repository, and future updates to Azure CLI will include the 64-bit version.  Thank you for reporting this!

**Comment by peterjohnsonme** [comment]
Closing issue.
